// Ghidra headless script: how does native mode reconfigure the device, and is there
// more than one configuration a host could select?
//
// Usage:
//   ~/Downloads/ghidra_12.1.2_PUBLIC/support/analyzeHeadless \
//     "<repo>/Resources/FirmwareAnalysis/ghidra_project" Motion32FirmwareFull \
//     -process motionupgrade.bin -noanalysis -readOnly \
//     -scriptPath "<repo>/Resources/FirmwareAnalysis" \
//     -postScript Motion32HostConfigProbe.java "<repo>/Resources/FirmwareAnalysis/host_config_probe.md"
//
// Why this probe exists. Earlier passes mapped the *outbound* event path completely but never
// found the `8F 00 7F` parser, because they searched the Fender SysEx framed queue. `8F 00 7F`
// is not SysEx at all — it is a **Note Off on channel 16** (status 0x80, channel 15 zero-based,
// note 0, velocity 127). So the switch lives in channel-voice handling, not the F0 path.
//
// Sections:
//   1. Channel-voice dispatch — where a status byte is decoded, and any 0x8F / 0x80+ch compare.
//   2. Inbound Fender SysEx command vocabulary — every command id the device will accept,
//      not just the 0x20/0x21/0x22 Studio Pro happens to use. This is the "what could we hook"
//      question stated directly.
//   3. FUN_*e50, the config selector — it chooses SysEx prefix, absolute/relative control
//      counts and the relative control-id order. What writes its selector?
//   4. The config tables themselves, dumped, so variant count is a fact rather than a guess.
//   5. Every reader of the candidate host-state flags — i.e. control by control, what actually
//      changes when native mode is entered.
//
// Addresses are DISCOVERED from stable RAM addresses rather than hardcoded, because the repo
// has two imports at different bases (Motion32Firmware vs Motion32FirmwareFull) and the earlier
// reports quote both (`FUN_000010a4` / old `FUN_000020a4`).

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSetView;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.InstructionIterator;
import ghidra.program.model.scalar.Scalar;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceManager;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

public class Motion32HostConfigProbe extends GhidraScript {

    /** Stable RAM anchors from NativeMode_USB_EventStream_Report.md. */
    private static final long QUEUE_INBOUND = 0x200040a0L;   // Fender framed-byte queue
    private static final long QUEUE_OUTBOUND = 0x20004084L;  // host event queue
    private static final long ABS_COUNT = 0x200045caL;       // absolute-control count (per config)
    private static final long REL_COUNT = 0x200045ccL;       // relative-control count (per config)
    private static final long STATE_CAND = 0x20004538L;      // candidate mode/state word

    /** Config/table data seen in the earlier survey. */
    private static final long[] TABLE_DUMPS = {
        0x9664L,  // per-config relative control-id order
        0x95fcL,  // scanned-control setup pairs
        0x9874L,  // USB descriptor/config struct
    };
    private static final int TABLE_LEN = 96;

    /** Status bytes worth hunting for in compares. */
    private static final long[] STATUS_CONSTANTS = {
        0x8fL,  // the native-entry Note Off status itself
        0x80L,  // Note Off family
        0x90L,  // Note On family
        0xb0L,  // Control Change
        0xe0L,  // Pitch Bend
        0xf0L,  // SysEx / status mask
        0x0fL,  // channel mask
    };

    private DecompInterface decomp;
    private PrintWriter out;

    @Override
    protected void run() throws Exception {
        String[] args = getScriptArgs();
        File target = new File(args.length > 0 ? args[0] : "host_config_probe.md");

        decomp = new DecompInterface();
        DecompileOptions options = new DecompileOptions();
        decomp.setOptions(options);
        decomp.openProgram(currentProgram);

        out = new PrintWriter(target, "UTF-8");
        try {
            out.println("# Motion 32 — host configuration probe");
            out.println();
            out.println("Program: `" + currentProgram.getName() + "`  ");
            out.println("Image base: `" + currentProgram.getImageBase() + "`  ");
            out.println("Generated by `Motion32HostConfigProbe.java`.");
            out.println();
            out.println("Three questions: how native mode takes each control over, whether more than");
            out.println("one configuration exists, and whether a handshake variation could select one.");
            out.println();

            sectionChannelVoice();
            sectionInboundCommands();
            sectionConfigSelector();
            sectionTables();
            sectionStateReaders();
            sectionBytePatterns();

            out.println();
            out.println("---");
            out.println();
            out.println("## What to read first");
            out.println();
            out.println("1. Section 1 — any function comparing against `0x8f`, or masking `0xf0`/`0x0f`");
            out.println("   on a received status byte. That is the native-entry parser the earlier");
            out.println("   passes could not find, and its neighbours are the other host commands.");
            out.println("2. Section 2 — the accepted Fender command ids. Anything beyond `0x20`/`0x21`/");
            out.println("   `0x22` is undocumented host->device vocabulary and a candidate hook.");
            out.println("3. Section 3 — if the config selector is written from anywhere other than a");
            out.println("   boot-time product-id read, a host can change configuration at runtime.");
        } finally {
            out.close();
            decomp.dispose();
        }
        println("Wrote " + target.getAbsolutePath());
    }

    // ---------------------------------------------------------------- section 1
    private void sectionChannelVoice() throws Exception {
        out.println("## 1. Channel-voice dispatch (where `8F 00 7F` is decoded)");
        out.println();
        out.println("`8F 00 7F` = Note Off, channel 16, note 0, velocity 127. Any function that");
        out.println("compares a byte against these constants is a candidate.");
        out.println();

        Map<Long, Set<String>> hits = new LinkedHashMap<>();
        for (long c : STATUS_CONSTANTS) {
            hits.put(c, new TreeSet<String>());
        }

        InstructionIterator it = currentProgram.getListing().getInstructions(true);
        while (it.hasNext() && !monitor.isCancelled()) {
            Instruction insn = it.next();
            for (int i = 0; i < insn.getNumOperands(); i++) {
                Scalar s = insn.getScalar(i);
                if (s == null) {
                    continue;
                }
                long v = s.getUnsignedValue();
                if (!hits.containsKey(v)) {
                    continue;
                }
                Function f = getFunctionContaining(insn.getAddress());
                String where = (f != null ? f.getName() + " @ " + f.getEntryPoint() : "(no function)")
                        + "  [" + insn.getAddress() + " " + insn + "]";
                hits.get(v).add(where);
            }
        }

        for (long c : STATUS_CONSTANTS) {
            Set<String> where = hits.get(c);
            out.println("### constant `0x" + Long.toHexString(c) + "` — " + where.size() + " site(s)");
            out.println();
            if (where.isEmpty()) {
                out.println("_none_");
            } else {
                out.println("```text");
                int n = 0;
                for (String w : where) {
                    out.println(w);
                    if (++n >= 60) {
                        out.println("... (" + (where.size() - n) + " more)");
                        break;
                    }
                }
                out.println("```");
            }
            out.println();
        }

        // The 0x8f sites are the money; decompile the functions containing them.
        Set<Function> interesting = new LinkedHashSet<>();
        InstructionIterator it2 = currentProgram.getListing().getInstructions(true);
        while (it2.hasNext() && !monitor.isCancelled()) {
            Instruction insn = it2.next();
            for (int i = 0; i < insn.getNumOperands(); i++) {
                Scalar s = insn.getScalar(i);
                if (s != null && s.getUnsignedValue() == 0x8fL) {
                    Function f = getFunctionContaining(insn.getAddress());
                    if (f != null) {
                        interesting.add(f);
                    }
                }
            }
        }
        out.println("### Decompilation of every function containing an `0x8f` compare");
        out.println();
        if (interesting.isEmpty()) {
            out.println("**No `0x8f` literal anywhere.** That is itself a finding: the status byte is");
            out.println("probably decoded by mask (`status & 0xf0`) plus a channel compare, or the USB-MIDI");
            out.println("code-index-number is used instead of the status byte. Check the `0xf0`/`0x0f`");
            out.println("sites above, and the USB packet decoder reachable from the endpoint config.");
            out.println();
        }
        for (Function f : interesting) {
            dumpFunction(f);
        }
    }

    // ---------------------------------------------------------------- section 2
    private void sectionInboundCommands() throws Exception {
        out.println("## 2. Inbound Fender SysEx command vocabulary");
        out.println();
        out.println("Everything that references the inbound framed queue `0x"
                + Long.toHexString(QUEUE_INBOUND) + "`, decompiled. The command dispatch");
        out.println("(a switch or compare chain on the byte after `F0 08 26`) tells us every command");
        out.println("the device accepts — including any Studio Pro never sends.");
        out.println();

        Set<Function> consumers = functionsReferencing(QUEUE_INBOUND);
        out.println("Functions referencing the inbound queue: **" + consumers.size() + "**");
        out.println();
        for (Function f : consumers) {
            dumpFunction(f);
            out.println("**Constants compared inside `" + f.getName() + "` (candidate command ids):**");
            out.println();
            out.println("```text");
            for (String line : scalarsIn(f)) {
                out.println(line);
            }
            out.println("```");
            out.println();
        }
    }

    // ---------------------------------------------------------------- section 3
    private void sectionConfigSelector() throws Exception {
        out.println("## 3. The configuration selector");
        out.println();
        out.println("`FUN_*e50` chooses the SysEx prefix, the absolute-control count, the relative-");
        out.println("control count and the relative control-id order. Found here by its writes to");
        out.println("`0x" + Long.toHexString(ABS_COUNT) + "` / `0x" + Long.toHexString(REL_COUNT) + "`.");
        out.println();

        Set<Function> selectors = new LinkedHashSet<>();
        selectors.addAll(functionsReferencing(ABS_COUNT));
        selectors.addAll(functionsReferencing(REL_COUNT));

        out.println("Functions touching the per-config counts: **" + selectors.size() + "**");
        out.println();
        for (Function f : selectors) {
            dumpFunction(f);
            out.println("**Callers of `" + f.getName() + "`** — this is what selects the configuration:");
            out.println();
            out.println("```text");
            Set<String> callers = new TreeSet<>();
            for (Reference r : getReferencesTo(f.getEntryPoint())) {
                Function c = getFunctionContaining(r.getFromAddress());
                callers.add(c != null ? c.getName() + " @ " + c.getEntryPoint()
                        : "(none) @ " + r.getFromAddress());
            }
            if (callers.isEmpty()) {
                out.println("(no direct references — may be called through a table)");
            }
            for (String c : callers) {
                out.println(c);
            }
            out.println("```");
            out.println();
        }
    }

    // ---------------------------------------------------------------- section 4
    private void sectionTables() throws Exception {
        out.println("## 4. Configuration tables, dumped");
        out.println();
        out.println("How many variants exist is a question about data, not code.");
        out.println();
        for (long base : TABLE_DUMPS) {
            Address a = toAddr(base);
            out.println("### `0x" + Long.toHexString(base) + "`");
            out.println();
            out.println("```text");
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < TABLE_LEN; i++) {
                if (i % 16 == 0) {
                    if (i > 0) {
                        out.println(sb.toString());
                        sb.setLength(0);
                    }
                    sb.append(String.format("%08x: ", base + i));
                }
                try {
                    sb.append(String.format("%02x ", currentProgram.getMemory().getByte(a.add(i)) & 0xff));
                } catch (Exception e) {
                    sb.append("?? ");
                }
            }
            out.println(sb.toString());
            out.println("```");
            out.println();
        }
    }

    // ---------------------------------------------------------------- section 5
    private void sectionStateReaders() throws Exception {
        out.println("## 5. Who reads the host/native state");
        out.println();
        out.println("Every function referencing the candidate state words. This is the direct answer to");
        out.println("\"how does it switch each control to host takeover\" — each reader is one behaviour");
        out.println("that changes when the flag flips.");
        out.println();

        long[] stateAddrs = { STATE_CAND, ABS_COUNT, REL_COUNT, QUEUE_OUTBOUND };
        for (long addr : stateAddrs) {
            Set<Function> readers = functionsReferencing(addr);
            out.println("### `0x" + Long.toHexString(addr) + "` — " + readers.size() + " referencing function(s)");
            out.println();
            out.println("```text");
            for (Function f : readers) {
                out.println(f.getName() + " @ " + f.getEntryPoint());
            }
            if (readers.isEmpty()) {
                out.println("(none)");
            }
            out.println("```");
            out.println();
        }
    }

    // ---------------------------------------------------------------- section 6
    /**
     * Raw byte-pattern search.
     *
     * Added after the first run against the full image found **no literal `0x8f` compare at
     * all** — the three `movs #0x8f` sites were 16-bit stores of `0x08f0`, i.e. the bytes
     * `F0 08`, so they build SysEx frames rather than decode a Note Off.
     *
     * If the status byte is never compared literally, the command may instead be matched
     * against a **template in memory**. A stored `8f 00 7f` / `8f 00 00` pair would be exactly
     * that, and a run of Fender command ids would be the dispatch table Section 2 is after.
     */
    private void sectionBytePatterns() throws Exception {
        out.println("## 6. Raw byte-pattern search");
        out.println();
        out.println("If no code compares `0x8f`, the command may be matched against a stored template.");
        out.println();

        byte[][] patterns = {
            { (byte) 0x8f, 0x00, 0x7f },        // native mode ON
            { (byte) 0x8f, 0x00, 0x00 },        // native mode OFF
            { (byte) 0xf0, 0x08, 0x26 },        // Fender header, Motion 32
            { (byte) 0xf0, 0x08, 0x24 },        // Fender header, Motion 16
            { (byte) 0xf0, 0x7e, 0x7f, 0x06 },  // Universal Identity Request
        };
        String[] names = {
            "8F 00 7F  (native ON)",
            "8F 00 00  (native OFF)",
            "F0 08 26  (Fender / Motion 32)",
            "F0 08 24  (Fender / Motion 16)",
            "F0 7E 7F 06  (Identity Request)",
        };

        for (int p = 0; p < patterns.length; p++) {
            out.println("### " + names[p]);
            out.println();
            out.println("```text");
            int found = 0;
            Address a = currentProgram.getMinAddress();
            while (a != null && a.compareTo(currentProgram.getMaxAddress()) < 0 && found < 40) {
                if (monitor.isCancelled()) {
                    break;
                }
                Address hit = currentProgram.getMemory().findBytes(
                        a, patterns[p], null, true, monitor);
                if (hit == null) {
                    break;
                }
                found++;
                StringBuilder ctx = new StringBuilder();
                for (int i = -8; i < 16; i++) {
                    try {
                        ctx.append(String.format("%02x ",
                                currentProgram.getMemory().getByte(hit.add(i)) & 0xff));
                    } catch (Exception e) {
                        ctx.append(".. ");
                    }
                }
                Function f = getFunctionContaining(hit);
                out.println(hit + "  " + ctx + "  "
                        + (f != null ? "in " + f.getName() : "(data)"));
                a = hit.add(1);
            }
            if (found == 0) {
                out.println("(not present)");
            }
            out.println("```");
            out.println();
        }
    }

    // ---------------------------------------------------------------- helpers
    private Set<Function> functionsReferencing(long addr) {
        Set<Function> found = new LinkedHashSet<>();
        ReferenceManager rm = currentProgram.getReferenceManager();
        for (Reference r : rm.getReferencesTo(toAddr(addr))) {
            Function f = getFunctionContaining(r.getFromAddress());
            if (f != null) {
                found.add(f);
            }
        }
        return found;
    }

    private List<String> scalarsIn(Function f) {
        Set<String> seen = new TreeSet<>();
        AddressSetView body = f.getBody();
        InstructionIterator it = currentProgram.getListing().getInstructions(body, true);
        while (it.hasNext()) {
            Instruction insn = it.next();
            for (int i = 0; i < insn.getNumOperands(); i++) {
                Scalar s = insn.getScalar(i);
                if (s == null) {
                    continue;
                }
                long v = s.getUnsignedValue();
                // Command ids are small; skip addresses and large immediates.
                if (v > 0 && v <= 0x7f) {
                    seen.add(String.format("0x%02x  (%s  %s)", v, insn.getAddress(), insn));
                }
            }
        }
        return new ArrayList<>(seen);
    }

    private void dumpFunction(Function f) {
        out.println("#### `" + f.getName() + "` @ `" + f.getEntryPoint() + "`");
        out.println();
        out.println("```c");
        try {
            DecompileResults res = decomp.decompileFunction(f, 90, monitor);
            if (res != null && res.decompileCompleted() && res.getDecompiledFunction() != null) {
                out.println(res.getDecompiledFunction().getC());
            } else {
                out.println("// decompilation failed: "
                        + (res != null ? res.getErrorMessage() : "no result"));
            }
        } catch (Exception e) {
            out.println("// decompilation threw: " + e);
        }
        out.println("```");
        out.println();
    }
}
